MrBen/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get(
//     '/localization/{language}',App\Http\Controllers\LocalizationController::class
// )->name('localization.switch');

Route::get(
    '/localization/{language}',
     App\Http\Controllers\LocalizationController::class, 'switch'
)->name('localization.switch');

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/about', [App\Http\Controllers\MrbenController::class, 'about'])->name('about');
Route::get('/', [App\Http\Controllers\MrbenController::class, 'home'])->name('Mrben.home');
Route::get('/post/{slug}', [App\Http\Controllers\MrbenController::class, 'showPostDetail'])->name('Mrben.posts.detail');
Route::get('/categories', [App\Http\Controllers\MrbenController::class, 'showCategories'])->name('Mrben.categories');
Route::get('/categories/{slug}', [App\Http\Controllers\MrbenController::class, 'showPostsCategory'])->name('Mrben.posts.category');
Route::get('/breeds', [App\Http\Controllers\MrbenController::class, 'showTags'])->name('Mrben.tags');
Route::get('/breeds/{slug}', [App\Http\Controllers\MrbenController::class, 'showPostsByTag'])->name('Mrben.posts.tag');
Route::get('/search', [App\Http\Controllers\MrbenController::class, 'searchPosts'])->name('Mrben.search');



Auth::routes([
    'register' => false
]);


Route::group(['prefix' => 'dashboard', 'middleware' => ['web','auth']], function () {
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard.index');
    //Categories
    Route::get('/categories/select',[\App\Http\Controllers\CategoryController::class, 'select'])->name('categories.select');
    Route::resource('/categories', \App\Http\Controllers\CategoryController::class);
    //tags
    Route::get('/tags/select',[\App\Http\Controllers\TagController::class, 'select'])->name('tags.select');
    Route::resource('/tags', \App\Http\Controllers\TagController::class)->except(['show']);
    //posts
    Route::resource('/posts', \App\Http\Controllers\PostController::class);
    //file manager
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/index',[\App\Http\Controllers\FileManagerController::class,'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();

    });
    //Roles
    Route::get('/roles/select',[\App\Http\Controllers\RoleController::class,'select'])->name('roles.select');
    Route::resource('/roles', \App\Http\Controllers\RoleController::class);
    //User
    Route::resource('/users', \App\Http\Controllers\UserController::class)->except(['show']);
});

MrBen/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    private $perPage = 3;
    public function __construct()
    {
        $this->middleware('permission:role_show',['only' => 'index']);
        $this->middleware('permission:role_create',['only' => 'create','store']);
        $this->middleware('permission:role_update',['only' => 'edit','update']);
        $this->middleware('permission:role_detail',['only' => 'show']);
        $this->middleware('permission:role_delete',['only' => 'destroy']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = [];
        if($request->has('keyword')){
            $roles =Role::where('name', 'LIKE', "%{$request->keyword}%")->paginate($this->perPage);
        }else{
            $roles = Role::paginate($this->perPage);
        }

        return view('roles.index', [
            'roles' => $roles->appends(['keyword' => $request->keyword])
        ]);
    }

    public function select(Request $request)
    {
        $roles = Role::select('id', 'name')->limit(7);
        if($request->has('q')){
            $roles->where('name', 'LIKE', "%{$request->q}%");
        }
        return response()->json($roles->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('roles.create',[
            'authorities' => config('permission.authorities')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            [
            'name' => "required|string|max:50|unique:roles,name",
            'permissions' => "required"
            ],
            [],
            $this->attributes()
    );
            if($validator->fails()){
                return redirect()->back()->withInput($request->all())->withErrors($validator);
            }
            
            DB::beginTransaction();
           try {
                $role = Role::create(['name' => $request->name]);
                $role->givePermissionTo($request->permissions);
                Alert::success(
                    trans('roles.alert.create.title'),
                    trans('roles.alert.create.message.success'),
                );
                return redirect()->route('roles.index');
           } catch (\Throwable $th) {
                DB::rollback();
                Alert::error(
                    trans('roles.alert.create.title'),
                    trans('roles.alert.create.message.error', ['error' => $th->getMessage()]),
                );
                return redirect()->back()->withInput($request->all());
           }finally{
                DB::commit();
           }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view ('roles.detail',[
            'role' => $role,
            'authorities' => config('permission.authorities'),
            'rolePermissions' => $role->permissions->pluck('name')->toArray()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('roles.edit',[
            'role' =>$role,
            'authorities' => config('permission.authorities'),
            'permissionChecked' => $role->permissions->pluck('name')->toArray()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $validator = Validator::make(
            $request->all(),
            [
            'name' => "required|string|max:50|unique:roles,name,". $role->id,
            'permissions' => "required"
            ],
            [],
            $this->attributes()
        );
            if($validator->fails()){
                return redirect()->back()->withInput($request->all())->withErrors($validator);
            }
            
            DB::beginTransaction();
            try {
                 $role->name = $request->name;
                 $role->syncPermissions($request->permissions);
                 $role->save();
                 Alert::success(
                     trans('roles.alert.update.title'),
                     trans('roles.alert.update.message.success'),
                 );
                 return redirect()->route('roles.index');
            } catch (\Throwable $th) {
                 DB::rollback();
                 Alert::error(
                     trans('roles.alert.update.title'),
                     trans('roles.alert.update.message.error', ['error' => $th->getMessage()]),
                 );
                 return redirect()->back()->withInput($request->all());
            }finally{
                 DB::commit();
            }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //validation
        if(User::role($role->name)->count()){
            Alert::warning(
                trans('roles.alert.delete.title'),
                trans('roles.alert.delete.message.warning',['name'=>$role->name]),
            );
            return redirect()->route('roles.index');
        }

        DB::beginTransaction();
        try {
            
             $role->revokePermissionTo($role->permissions->pluck('name')->toArray());
             $role->delete();
             Alert::success(
                 trans('roles.alert.delete.title'),
                 trans('roles.alert.delete.message.success'),
             );
        } catch (\Throwable $th) {
             DB::rollback();
             Alert::error(
                 trans('roles.alert.delete.title'),
                 trans('roles.alert.delete.message.error', ['error' => $th->getMessage()]),
             );
        }finally{
             DB::commit();
        }
        return redirect()->route('roles.index');
    }

    private function attributes()
    {
        return [
            'name' => trans('roles.form_control.input.name.attribute'),
            'permissions' => trans('roles.form_control.input.permission.attribute'),
        ];
    }
}

MrBen/resources/views/roles/create.blade.php
@extends('layouts.dashboard')

@section('title')
     {{trans('roles.title.create')}}
@endsection

@section('breadcrumbs')
{{ Breadcrumbs::render('add_role') }}
@endsection

@section('content')
<div class="row">
   <div class="col-md-12">
      <div class="card">
         <form action="{{route('roles.store')}}" method="POST">
            @csrf
            <div class="card-body">
               <div class="form-group">
                  <label for="input_role_name" class="font-weight-bold">
                     {{trans('roles.form_control.input.name.label')}}
                  </label>
                  <input id="input_role_name" value="{{old('name')}}" name="name" type="text"
                   class="form-control @error('name') is-invalid @enderror"/>
                   @error('name')
                    <span class="invalid-feedback">
                        <strong>
                            {{$message}}
                        </strong>
                    </span>
                   @enderror
               </div>
               <!-- permission -->
               <div class="form-group">
                  <label for="input_role_permission" class="font-weight-bold">
                  {{trans('roles.form_control.input.permission.label')}}
                  </label>
                  <div class="form-control overflow-auto h-100 @error('permissions') is-invalid @enderror" id="input_role_permission">
                     <div class="row">
                        @foreach ($authorities as $manageName => $permissions)
                        <ul class="list-group mx-1">
                           <li class="list-group-item bg-dark text-white">
                              {{trans("permissions.{$manageName}")}}
                           </li>
                           <!-- list permission:start -->
                           @foreach ($permissions as $permission)
                           <li class="list-group-item">
                              <div class="form-check">
                                @if (old('permissions'))
                                <input id="{{ $permission }}" name="permissions[]" 
                                 class="form-check-input" type="checkbox" value="{{$permission}}" 
                                 {{ in_array($permission,old('permissions')) ? "checked" : null}}>
                                @else
                                <input id="{{ $permission }}" name="permissions[]" 
                                 class="form-check-input" type="checkbox" value="{{$permission}}">
                                @endif
                                 
                                 <label for="{{$permission}}" class="form-check-label">
                                 {{trans("permissions.{$permission}")}}
                                 </label>
                              </div>
                           </li>
                           @endforeach
                           <!-- list permission:end -->
                        </ul>
                        @endforeach

                        <!-- list manage name:start -->
                        <!-- list manage name:end  -->
                     </div>
                  </div>
                  @error('permissions')
                    <span class="invalid-feedback">
                        <strong>
                            {{$message}}
                        </strong>
                    </span>
                   @enderror
               </div>
               <div class="float-right mb-4">
                  <a class="btn btn-warning px-4 mx-2" href="">
                  {{trans('roles.button.back.value')}}
                  </a>
                  <button type="submit" class="btn btn-primary px-4">
                  {{trans('roles.button.save.value')}}
                  </button>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>
@endsection

MrBen/resources/views/roles/detail.blade.php
@extends('layouts.dashboard')

@section('title')
     {{trans('roles.title.detail')}}
@endsection

@section('breadcrumbs')
{{ Breadcrumbs::render('detail_role', $role) }}
@endsection

@section('content')
<div class="row">
   <div class="col-md-12">
      <div class="card">
         <div class="card-body">
            <div class="form-group">
               <label for="input_role_name" class="font-weight-bold">
                 {{ trans('roles.form_control.input.name.label')}}
               </label>
               <input id="input_role_name" value="{{$role->name}}" name="name" type="text" class="form-control" readonly />
            </div>
            <!-- permission -->
            <div class="form-group">
               <label for="input_role_permission" class="font-weight-bold">
               {{ trans('roles.form_control.input.permission.label')}}
               </label>
               <div class="row">
                @forelse ($authorities as $manageName => $permissions)
                       <!-- list manage name:start -->
                  <ul class="list-group mx-1">
                     <li class="list-group-item bg-dark text-white">
                        {{trans("permissions.{$manageName}") }}
                     </li>
                     <!-- list permission:start -->
                     @foreach ($permissions as $permission)
                     <li class="list-group-item">
                        <div class="form-check">
                           <input class="form-check-input" type="checkbox"
                              value="" onclick="return false;" 
                              {{in_array($permission, $rolePermissions) ? 'checked' : null }}>
                           <label class="form-check-label">
                           {{trans("permissions.{$permission}") }}
                           </label>
                        </div>
                     </li>
                     @endforeach
                     <!-- list permission:end -->
                  </ul>
                @empty
                  <p>
                     <strong>
                        {{trans('roles.label.no_data.fetch')}}
                     </strong>
                  </p>
                @endforelse
                  <!-- list manage name:end  -->
               </div>
            </div>
            <!-- button  -->
            <div class="d-flex justify-content-end">
               <a href="{{route('roles.index')}}" class="btn btn-primary mx-1" role="button">
                  {{trans('roles.button.back.value')}}
               </a>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

MrBen/resources/views/roles/edit.blade.php
@extends('layouts.dashboard')

@section('title')
     {{trans('roles.title.edit')}}
@endsection

@section('breadcrumbs')
{{ Breadcrumbs::render('edit_role', $role) }}
@endsection

@section('content')
<div class="row">
   <div class="col-md-12">
      <div class="card">
         <form action="{{route('roles.update',['role' => $role])}}" method="POST">
            @csrf
            @method('PUT')
            <div class="card-body">
               <div class="form-group">
                  <label for="input_role_name" class="font-weight-bold">
                     {{trans('roles.form_control.input.name.label')}}
                  </label>
                  <input id="input_role_name" value="{{old('name', $role->name)}}" name="name" type="text"
                   class="form-control @error('name') is-invalid @enderror"/>
                   @error('name')
                    <span class="invalid-feedback">
                        <strong>
                            {{$message}}
                        </strong>
                    </span>
                   @enderror
               </div>
               <!-- permission -->
               <div class="form-group">
                  <label for="input_role_permission" class="font-weight-bold">
                  {{trans('roles.form_control.input.permission.label')}}
                  </label>
                  <div class="form-control overflow-auto h-100 @error('permissions') is-invalid @enderror" id="input_role_permission">
                     <div class="row">
                        @foreach ($authorities as $manageName => $permissions)
                        <ul class="list-group mx-1">
                           <li class="list-group-item bg-dark text-white">
                              {{trans("permissions.{$manageName}")}}
                           </li>
                           <!-- list permission:start -->
                           @foreach ($permissions as $permission)
                           <li class="list-group-item">
                              <div class="form-check">
                                @if (old('permissions', $permissionChecked))
                                <input id="{{ $permission }}" name="permissions[]" 
                                 class="form-check-input" type="checkbox" value="{{$permission}}" 
                                 {{ in_array($permission,old('permissions', $permissionChecked)) ? "checked" : null}}>
                                @else
                                <input id="{{ $permission }}" name="permissions[]" 
                                 class="form-check-input" type="checkbox" value="{{$permission}}">
                                @endif
                                 
                                 <label for="{{$permission}}" class="form-check-label">
                                 {{trans("permissions.{$permission}")}}
                                 </label>
                              </div>
                           </li>
                           @endforeach
                           <!-- list permission:end -->
                        </ul>
                        @endforeach
                     </div>
                  </div>
                  @error('permissions')
                    <span class="invalid-feedback">
                        <strong>
                            {{$message}}
                        </strong>
                    </span>
                   @enderror
               </div>
               <div class="float-right mb-4">
                  <a class="btn btn-warning px-4 mx-2" href="{{route('roles.index')}}">
                  {{trans('roles.button.back.value')}}
                  </a>
                  <button type="submit" class="btn btn-primary px-4">
                  {{trans('roles.button.edit.value')}}
                  </button>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>
@endsection

MrBen/resources/views/roles/index.blade.php
@extends('layouts.dashboard')

@section('title')
     {{trans('roles.title.index')}}
@endsection

@section('breadcrumbs')
{{ Breadcrumbs::render('roles') }}
@endsection

@section('content')
<!-- section:content -->
<div class="row">
   <div class="col-md-12">
      <div class="card">
         <div class="card-header">
           <div class="row">
               <div class="col-md-6">
                  <form action="{{route('roles.index')}}" method="GET">
                     <div class="input-group">
                        <input name="keyword" value="{{ request()->get('keyword') }}" type="search" class="form-control" 
                        placeholder="{{ trans('roles.form_control.input.search.placeholder')}}">
                        <div class="input-group-append">
                           <button class="btn btn-primary" type="submit">
                              <i class="fas fa-search"></i>
                           </button>
                        </div>
                     </div>
                  </form>
               </div>
               <div class="col-md-6">
                  @can('role_create')
                  <a href="{{ route('roles.create')}}" class="btn btn-primary float-right" role="button">
                     {{trans('roles.button.create.value')}}
                     <i class="fas fa-plus-square"></i>
                  </a>
                  @endcan
               </div>
            </div>
         </div>
         <div class="card-body">
            <ul class="list-group list-group-flush">
               <!-- list role -->
               @forelse ($roles as $role)
               <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center pr-0">
                     <label class="mt-auto mb-auto">
                        {{$role->name}}
                        </label>
                        <div>
                            <!-- detail -->
                            @can('role_detail')
                            <a href="{{ route('roles.show', ['role' => $role]) }}" class="btn btn-sm btn-primary"
                            role="button">
                            <i class="fas fa-eye"></i>
                            </a>
                            @endcan
                           <!-- edit -->
                           @can('role_update')
                           <a href="{{ route('roles.edit',['role' =>$role]) }}" class="btn btn-sm btn-info" role="button">
                              <i class="fas fa-edit"></i>
                           </a>
                           @endcan
                           <!-- delete -->
                           @can('role_delete')
                           <form class="d-inline" role="alert"
                           alert-text="{{ trans('roles.alert.delete.message.confirm', ['name' => $role->name]) }}" 
                           action="{{ route('roles.destroy', ['role'=>$role]) }}" method="POST">
                           @csrf
                           @method('DELETE')
                           <button type="submit" class="btn btn-sm btn-danger">
                                 <i class="fas fa-trash"></i>
                           </button>
                           </form>
                           @endcan
                        </div>
                     </li>
               @empty
                <p>
                    <strong>
                        @if(request()->get('keyword'))
                           {{ trans('roles.label.no_data.search',['keyword' => request()->get('keyword')]) }}
                        @else
                           {{ trans('roles.label.no_data.fetch') }}
                        @endif
                    </strong>
                </p>
               @endforelse
                     <!-- list role -->
            </ul>
         </div>
         @if ($roles->hasPages())
            <div class="card-footer">
                {{ $roles->links('vendor.pagination.bootstrap-4')}}
            </div>
         @endif
      </div>
   </div>
</div>
@endsection


@push('javascript-internal')
   <script>
      $(document).ready(function(){

         //delete tag
         $("form[role='alert']").submit(function(){
            Swal.fire({
            title: "{{ trans('roles.alert.delete.title') }}",
            text: $(this).attr('alert-text'),
            icon: 'warning',
            allowOutsideClick: false,
            showCancelButton: true,
            cancelButtonText: "{{ trans('roles.button.cancel.value') }}",
            reverseButtons: true,
            confirmButtonText: "{{ trans('roles.button.delete.value') }}",
         }).then((result) => {
            if (result.isConfirmed) {
               event.target.submit();
            }
      });



         });
      });
   </script>
@endpush