MrBen/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get(
//     '/localization/{language}',App\Http\Controllers\LocalizationController::class
// )->name('localization.switch');

Route::get(
    '/localization/{language}',
     App\Http\Controllers\LocalizationController::class, 'switch'
)->name('localization.switch');

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/about', [App\Http\Controllers\MrbenController::class, 'about'])->name('about');
Route::get('/', [App\Http\Controllers\MrbenController::class, 'home'])->name('Mrben.home');
Route::get('/post/{slug}', [App\Http\Controllers\MrbenController::class, 'showPostDetail'])->name('Mrben.posts.detail');
Route::get('/categories', [App\Http\Controllers\MrbenController::class, 'showCategories'])->name('Mrben.categories');
Route::get('/categories/{slug}', [App\Http\Controllers\MrbenController::class, 'showPostsCategory'])->name('Mrben.posts.category');
Route::get('/breeds', [App\Http\Controllers\MrbenController::class, 'showTags'])->name('Mrben.tags');
Route::get('/breeds/{slug}', [App\Http\Controllers\MrbenController::class, 'showPostsByTag'])->name('Mrben.posts.tag');
Route::get('/search', [App\Http\Controllers\MrbenController::class, 'searchPosts'])->name('Mrben.search');



Auth::routes([
    'register' => false
]);


Route::group(['prefix' => 'dashboard', 'middleware' => ['web','auth']], function () {
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard.index');
    //Categories
    Route::get('/categories/select',[\App\Http\Controllers\CategoryController::class, 'select'])->name('categories.select');
    Route::resource('/categories', \App\Http\Controllers\CategoryController::class);
    //tags
    Route::get('/tags/select',[\App\Http\Controllers\TagController::class, 'select'])->name('tags.select');
    Route::resource('/tags', \App\Http\Controllers\TagController::class)->except(['show']);
    //posts
    Route::resource('/posts', \App\Http\Controllers\PostController::class);
    //file manager
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/index',[\App\Http\Controllers\FileManagerController::class,'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();

    });
    //Roles
    Route::get('/roles/select',[\App\Http\Controllers\RoleController::class,'select'])->name('roles.select');
    Route::resource('/roles', \App\Http\Controllers\RoleController::class);
    //User
    Route::resource('/users', \App\Http\Controllers\UserController::class)->except(['show']);
});

MrBen/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable = [
        "title",
        "slug",
        "thumbnail",
        "description",
        "content",
        "status",
        "user_id",
    ];

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTimestamps();
    }

    public function scopeSearch($query, $title)
    {
        return $query->where('title', 'LIKE', "%{$title}%");
    }

    public function scopePublish($query)
    {
        return $query->where('status', "publish");
    }

    public function scopeDraft($query)
    {
        return $query->where('status', "draft");
    }
}

MrBen/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;


class PostController extends Controller
{
    // 'manage_posts' => [
    //     'post_show',
    //     'post_create',
    //     'post_update',
    //     'post_detail',
    //     'post_delete'
    // ],
    public function __construct()
{
    $this->middleware('permission:post_show',['only' => 'index']);
    $this->middleware('permission:post_create',['only' => 'create','store']);
    $this->middleware('permission:post_update',['only' => 'edit','update']);
    $this->middleware('permission:post_detail',['only' => 'show']);
    $this->middleware('permission:post_delete',['only' => 'destroy']);
}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $statusSelected = in_array($request->get('status'),['publish','draft']) ? $request->get('status') : "publish";
        $posts =  $statusSelected == "publish" ? Post::publish() : Post::draft();
        if ($request->get('keyword')){
            $posts->search($request->get('keyword'));
        }
        return view ('posts.index', [
            'posts' => $posts->paginate(3)->withQueryString(),
            'status' => $this->status(),
            'statusSelected' => $statusSelected
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create',[
            'categories' => Category::with('descendants')->onlyParent()->get(),
            'status' => $this->status()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'title' => 'required|string|max:60',
                'slug' => 'required|string|unique:posts,slug',
                'thumbnail' => 'required',
                'description' => 'required|string|max:240',
                'content' => 'required',
                'category' => 'required',
                'tag' => 'required',
                'status' => 'required'
            ],
            [],
            $this->attributes()
    );
        if($validator->fails()){
            if ($request['tag']) {
                $request['tag'] = Tag::select('id','title')->whereIn('id', $request->tag)->get();
            }

            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }

        DB::beginTransaction();
        try {
            $post = Post::create([
                "title" => $request->title,
                "slug" => $request->slug,
                "thumbnail" => parse_url($request->thumbnail)['path'],
                "description" => $request->description,
                "content" => $request->content,
                "status" => $request->status,
                "user_id" => Auth::user()->id,
            ]);
            $post->tags()->attach($request->tag);
            $post->categories()->attach($request->category);

            Alert::success(
                trans('posts.alert.create.title'),
                trans('posts.alert.create.message.success'),
            );
            return redirect()->route('posts.index');
        } catch (\Throwable $th) {
            DB::rollback();
            Alert::error(
                trans('posts.alert.create.title'),
                trans('posts.alert.create.message.error', ['error' => $th->getMessage()]),
            );
            if ($request['tag']) {
                $request['tag'] = Tag::select('id','title')->whereIn('id', $request->tag)->get();
            }

            return redirect()->back()->withInput($request->all());
        }finally{
            DB::commit();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $categories = $post->categories;
        $tags = $post->tags;
        return view ('posts.detail',compact('post','categories','tags'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view ('posts.edit',[
            'post' => $post,
            'categories' => Category::with('descendants')->onlyParent()->get(),
            'status' => $this->status()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'title' => 'required|string|max:60',
                'slug' => 'required|string|unique:posts,slug,' . $post->id,
                'thumbnail' => 'required',
                'description' => 'required|string|max:240',
                'content' => 'required',
                'category' => 'required',
                'tag' => 'required',
                'status' => 'required'
            ],
            [],
            $this->attributes()
    );
        if($validator->fails()){
            if ($request['tag']) {
                $request['tag'] = Tag::select('id','title')->whereIn('id', $request->tag)->get();
            }

            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }
        
        DB::beginTransaction();
        try {
            $post->update([
                "title" => $request->title,
                "slug" => $request->slug,
                "thumbnail" => parse_url($request->thumbnail)['path'],
                "description" => $request->description,
                "content" => $request->content,
                "status" => $request->status,
                "user_id" => Auth::user()->id,
            ]);
            $post->tags()->sync($request->tag);
            $post->categories()->sync($request->category);

            Alert::success(
                trans('posts.alert.update.title'),
                trans('posts.alert.update.message.success'),
            );
            return redirect()->route('posts.index');
        } catch (\Throwable $th) {
            DB::rollback();
            Alert::error(
                trans('posts.alert.update.title'),
                trans('posts.alert.update.message.error', ['error' => $th->getMessage()]),
            );
            if ($request['tag']) {
                $request['tag'] = Tag::select('id','title')->whereIn('id', $request->tag)->get();
            }

            return redirect()->back()->withInput($request->all());
        }finally{
            DB::commit();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        DB::beginTransaction();
        try {
            $post->tags()->detach();
            $post->categories()->detach();
            $post->delete();
         
            Alert::success(
                trans('posts.alert.delete.title'),
                trans('posts.alert.delete.message.success'),
            );
            return redirect()->route('posts.index');
        } catch (\Throwable $th) {
            DB::rollback();
            Alert::error(
                trans('posts.alert.delete.title'),
                trans('posts.alert.delete.message.error', ['error' => $th->getMessage()]),
            );
        }finally{
            DB::commit();
            return redirect()->back();
        }
    }

    private function status()
    {
        return [
            'draft' => trans('posts.form_control.select.status.option.draft'),
            'publish' => trans('posts.form_control.select.status.option.publish'),
        ];
    }
    private function attributes()
    {
        return [
                'title' => trans('posts.form_control.input.title.attribute'),
                'slug' => trans('posts.form_control.input.slug.attribute'),
                'thumbnail' => trans('posts.form_control.input.thumbnail.attribute'),
                'description' => trans('posts.form_control.textarea.description.attribute'),
                'content' => trans('posts.form_control.textarea.content.attribute'),
                'category' => trans('posts.form_control.input.category.attribute'),
                'tag' => trans('posts.form_control.select.tag.attribute'),
                'status' => trans('posts.form_control.select.status.attribute')
        ];
    }
}

MrBen/resources/views/posts/_category-list.blade.php
<ul class="pl-1 my-1" style="list-style: none;">
        @foreach ($categories as $category)
            <li class="form-group form-check my-1">
                @if($categoryChecked && in_array($category->id, $categoryChecked))
                <input class="form-check-input" value="{{ $category->id }}" type="checkbox" name="category[]" checked>
                @else
                <input class="form-check-input" value="{{ $category->id }}" type="checkbox" name="category[]">
                @endif      
                        <label class="form-check-label">
                            {{ $category->title }}
                        </label>
                        @if ($category->descendants)
                            @include('posts._category-list',[
                                'categories' => $category->descendants,
                                'categoryChecked' => $categoryChecked
                                ])
                        @endif
             </li>
         @endforeach
 </ul>

MrBen/resources/views/posts/detail.blade.php
@extends('layouts.dashboard')

@section('title')
     {{trans('posts.title.detail')}}
@endsection

@section('breadcrumbs')
{{ Breadcrumbs::render('detail_post', $post) }}
@endsection

@section('content')
<div class="row">
      <div class="col-md-12">
         <div class="card">
            <div class="card-body">
                @if (file_exists(public_path($post->thumbnail)))
                <!-- thumbnail:true -->
               <div class="post-tumbnail" style="background-image: url('{{ $post->thumbnail }}');">
               </div>
                @else
            <!-- thumbnail:false -->
               <svg class="img-fluid" width="100%" height="400" xmlns="http://www.w3.org/2000/svg"
                  preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
                  <rect width="100%" height="100%" fill="#868e96"></rect>
                  <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#dee2e6" dy=".3em"
                     font-size="24">
                      {{ $post->title }}
                     </text>
               </svg>
                @endif
               <!-- title -->
               <h2 class="my-1">
               {{ $post->title }}
               </h2>
               <!-- description -->
               <p class="text-justify">
               {{ $post->description }}
               </p>
               <!-- categories -->
               @foreach ($categories as $category)
                <span class="badge badge-primary">{{ $category->title }}</span>
                @endforeach
               <!-- content -->
               <div class="py-1">
               {!! $post->content !!}
               </div>
               <!-- tags  -->
               @foreach ($tags as $tag)
                <span class="badge badge-info">#{{ $tag->title }}</span>
               @endforeach
               <div class="d-flex justify-content-end">
                  <a href="{{route('posts.index')}}" class="btn btn-primary mx-1" role="button">
                     {{trans('posts.button.back.value')}}
                  </a>
               </div>
            </div>
         </div>
      </div>
   </div>
@endsection

@push('css-internal')
<style>
  .post-tumbnail {
   width: 100%;
   height: 400px;
   background-repeat: no-repeat;
   background-position: center;
   background-size: cover;
}
</style>
@endpush

MrBen/resources/views/posts/index.blade.php
@extends('layouts.dashboard')

@section('title')
     {{trans('posts.title.index')}}
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('posts')}}
@endsection

@section('content')
<div class="row">
  <div class="col-md-12">
     <div class="card">
        <div class="card-header">
           <div class="row">
              <div class="col-md-6">
                 <form action="" method="GET" class="form-inline form-row">
                    <div class="col">
                       <div class="input-group mx-1">
                          <label class="font-weight-bold mr-2">
                            {{ trans('posts.form_control.select.status.label')}}
                          </label>
                          <select name="status" class="custom-select">
                           @foreach ($status as $value => $label)
                           <option value="{{ $value }}" 
                           {{$statusSelected == $value ? 'selected' : null}}> 
                              {{ $label }}
                           </option>
                           @endforeach
                          </select>
                          <div class="input-group-append">
                             <button class="btn btn-primary" type="submit">
                             {{ trans('posts.button.apply.value')}}
                             </button>
                          </div>
                       </div>
                    </div>
                    <div class="col">
                       <div class="input-group mx-1">
                          <input name="keyword" value="{{ request()->get('keyword') }}" type="search" class="form-control" 
                          placeholder="{{ trans('posts.form_control.input.search.placeholder') }}">
                          <div class="input-group-append">
                             <button class="btn btn-primary" type="submit">
                                <i class="fas fa-search"></i>
                             </button>
                          </div>
                       </div>
                    </div>
                 </form>
              </div>
              <div class="col-md-6">
              @can('post_create')
               <a href="{{ route('posts.create') }}" class="btn btn-primary float-right" role="button">
                 {{ trans('posts.button.create.value')}}
                    <i class="fas fa-plus-square"></i>
                 </a>
               @endcan
              </div>
           </div>
        </div>
        <div class="card-body">
           <ul class="list-group list-group-flush">
              <!-- list post -->
              @forelse ($posts as $post)
               <div class="card my-2">
                <div class="card-body">
                    <h5>
                        {{ $post->title }}
                    </h5>
                    <p>
                    {{ $post->description }}
                    </p>
                    <div class="float-right">
                       <!-- detail -->
                     @can ('post_detail')
                        <a href="{{route('posts.show', ['post' => $post]) }}" class="btn btn-sm btn-primary" role="button">
                            <i class="fas fa-eye"></i>
                        </a>
                     @endcan
                      <!-- edit -->
                      @can('post_update')
                       <a href="{{ route('posts.edit', ['post' => $post]) }}"class="btn btn-sm btn-info" role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                      @endcan
                        <!-- delete -->
                        @can('post_delete')
                        <form class="d-inline" role="alert"
                           alert-text="{{ trans('posts.alert.delete.message.confirm', ['title' => $post->title]) }}" 
                           action="{{ route('posts.destroy', ['post'=>$post]) }}" method="POST">
                           @csrf
                           @method('DELETE')
                           <button type="submit" class="btn btn-sm btn-danger">
                                 <i class="fas fa-trash"></i>
                        </button>
                        </form>
                        @endcan
                    </div>
                </div>
                </div>
              @empty
                    <p>
                        <strong>
                           @if(request()->get('keyword'))
                            {{ trans('posts.label.no_data.search',['keyword' => request()->get('keyword')]) }}
                           @else
                           {{trans('posts.label.no_data.fetch')}}
                           @endif
                        </strong>
                    </p>
              @endforelse
           </ul>
        </div>
        @if($posts->hasPages())
         <div class="card-footer">
            {{$posts->links('vendor.pagination.bootstrap-4')}}
         </div>
        @endif
     </div>
  </div>
</div>
@endsection

@push('javascript-internal')
   <script>
      $(document).ready(function(){

         //delete post
         $("form[role='alert']").submit(function(){
            Swal.fire({
            title: "{{ trans('posts.alert.delete.title') }}",
            text: $(this).attr('alert-text'),
            icon: 'warning',
            allowOutsideClick: false,
            showCancelButton: true,
            cancelButtonText: "{{ trans('posts.button.cancel.value') }}",
            reverseButtons: true,
            confirmButtonText: "{{ trans('posts.button.delete.value') }}",
         }).then((result) => {
            if (result.isConfirmed) {
               event.target.submit();
            }
      });

         });
      });
   </script>
@endpush